import PDFDocument from "pdfkit";
import { AnalysisResult } from "./ruleEngine";

export function generatePDFReport(
    analysis: AnalysisResult,
    reportId: string,
    timestamp: string
): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument();
            const buffers: Buffer[] = [];

            doc.on("data", (buffer) => buffers.push(buffer));
            doc.on("end", () => resolve(Buffer.concat(buffers)));
            doc.on("error", (err) => reject(err));

            // Header
            doc.fontSize(20).text("EMERGENCY INCIDENT REPORT", { align: "center" });
            doc.moveDown();
            doc.fontSize(12).text(`Report ID: ${reportId}`);
            doc.text(`Time: ${timestamp}`);
            doc.moveDown();
            doc.moveDown();

            // Summary Section
            doc.fontSize(16).text("Incident Summary");
            doc.moveDown(0.5);
            doc.fontSize(12).text(analysis.summary);
            doc.moveDown();

            // Critical Details Table-like structure
            doc.rect(50, doc.y, 500, 140).stroke();
            const startY = doc.y + 10;

            doc.text(`Harassment Type: ${analysis.harassment_type.replace(/_/g, " ")}`, 60, startY);

            if (analysis.name_detected && analysis.name_detected !== "unknown") {
                doc.fillColor("blue").text(`Victim Name: ${analysis.name_detected}`, 60, startY + 20);
                doc.fillColor("black");
            } else {
                doc.text(`Victim Name: Not Disclosed/Unknown`, 60, startY + 20);
            }

            doc.text(`Severity Level: ${analysis.severity}`, 60, startY + 40);
            doc.text(`Risk Score: ${analysis.risk_score}`, 60, startY + 60);
            doc.text(`Confidence: ${(analysis.confidence_score * 100).toFixed(1)}%`, 60, startY + 80);
            doc.text(`Emotions: ${analysis.emotion_detected.join(", ") || "None"}`, 60, startY + 100);

            doc.font("Helvetica-Bold").text(`Location: ${analysis.location_detected.toUpperCase()}`, 60, startY + 120);
            doc.font("Helvetica");

            doc.y = startY + 140;
            doc.moveDown();

            // Analysis Description
            doc.fontSize(16).text("Detailed Analysis", 50);
            doc.moveDown(0.5);
            doc.fontSize(12).text(analysis.description);
            doc.moveDown();

            // Danger Signals
            if (analysis.danger_signals.length > 0) {
                doc.fontSize(14).fillColor("red").text("⚠️ Danger Signals Detected:");
                doc.fillColor("black").fontSize(12);
                analysis.danger_signals.forEach((signal) => {
                    doc.text(`• ${signal}`);
                });
                doc.moveDown();
            }

            // Recommended Actions
            doc.fontSize(16).text("Recommended Immediate Actions");
            doc.moveDown(0.5);
            doc.fontSize(12);
            analysis.recommended_actions.forEach((action, index) => {
                doc.text(`${index + 1}. ${action}`);
            });
            doc.moveDown();

            // Footer
            doc.moveDown(2);
            doc.fontSize(10).text("Generated by SpeakSpace Emergency Detection System", { align: "center", textIndent: 0 });

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
}
