import { v4 as uuidv4 } from "uuid";
import { AnalysisResult } from "./ruleEngine";

export interface GeneratedReport {
  report_id: string;
  note_id: string;
  timestamp: string;
  formatted_report: string;
  analysis: AnalysisResult;
}

export function generateReport(
  analysis: AnalysisResult,
  noteId: string,
  timestamp: string,
  rawInput: string
): GeneratedReport {
  const reportId = uuidv4();
  
  const actionsFormatted = analysis.recommended_actions
    .map((action, index) => `  ${index + 1}. ${action}`)
    .join("\n");
  
  const emotionsFormatted = analysis.emotion_detected.length > 0
    ? analysis.emotion_detected.join(", ")
    : "None detected";
  
  const dangerSignalsFormatted = analysis.danger_signals.length > 0
    ? analysis.danger_signals.join(", ")
    : "None detected";
  
  const formattedReport = `
===== EMERGENCY INCIDENT REPORT =====

Report ID: ${reportId}
Note ID: ${noteId}
Time: ${timestamp}

Input Summary:
${analysis.summary}

Extracted Details:
- Harassment Type: ${analysis.harassment_type.replace(/_/g, " ")}
- Severity Level: ${analysis.severity}
- Victim Risk Level: ${analysis.victim_risk}
- Detected Emotions: ${emotionsFormatted}
- Risk Score: ${analysis.risk_score}
- Confidence Score: ${(analysis.confidence_score * 100).toFixed(1)}%
- Danger Signals: ${dangerSignalsFormatted}
- Possible Location: ${analysis.location_detected}
- Emergency Response Needed: ${analysis.needs_emergency_response ? "YES" : "NO"}

Recommended Immediate Actions:
${actionsFormatted}

Analysis Description:
${analysis.description}

Full User Input:
${rawInput}

=====================================
Generated by SpeakSpace Emergency Detection System
`.trim();

  return {
    report_id: reportId,
    note_id: noteId,
    timestamp,
    formatted_report: formattedReport,
    analysis
  };
}
